### ISSUE TITLE
monte carlo: verify_lat_lon

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#10]
General Monte Carlo overview plan is [here](https://docs.google.com/document/d/1MRDCViRZelm_RPVUDd67SdIufYHI4-KdcpwK9zCXxnY/edit)

Function: verify_lat_lon

This function will check whether selected lat/lon from GeoTiff file is:
1) Within Salish Sea Cast model boundary
2) On a Salish Sea Cast water point (i.e not on land)

**Comment by RachaelDMueller** [comment]
@SusanEAllen, can I mark this as closed?

**Comment by SusanEAllen** [comment]
Yes, we do not need to verify_lat_lon as being in the water because the lat_lon chooser can only chose SalishSeaCast water points by design.
