### ISSUE TITLE
monte carlo: calc_oil_capacity

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#14]
General Monte Carlo overview plan is[ here](https://docs.google.com/document/d/1MRDCViRZelm_RPVUDd67SdIufYHI4-KdcpwK9zCXxnY/edit)

Function: calc_oil_capacity 
Input: vessel length
Based on Krista’s line fits
Output: Oil capacity

**Comment by RachaelDMueller** [comment]
@campower, is there a place where the equations are listed out by vessel type; or shall I refer to the google spreadsheet in which Krista used excel to calculate the relationships?

**Comment by campower** [comment]
@RachaelDMueller, the equations are listed on the charts in [Krista's spreadsheet](https://docs.google.com/spreadsheets/d/1G2DYXY7prpQACmWRYPmc_ZVfn9HzVZY23ATr8poGtIA/edit#gid=1376382018), on the second tab.

**Comment by RachaelDMueller** [comment]
[This script](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_oil_capacity.py) does not put upper bounds on capacity for the exponential fits.  @SusanEAllen, this omission is not an oversight, I just think we may want to impose this upper limit on the spill volume instead of capacity. I’m closing the issue for now, but we can revisit/modify if/as needed.
