### ISSUE TITLE
monte carlo: define_oil_type

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#15]
General Monte Carlo overview plan is[ here](https://docs.google.com/document/d/1MRDCViRZelm_RPVUDd67SdIufYHI4-KdcpwK9zCXxnY/edit)

Function: define_oil_type 
1. for tank traffic
Input: vessel_type, origin/destination
Use DOE data for U.S. origin/destinations OR choose simplified approach
Output: Oil type
2. for non-tank traffic
Input: vessel type

**Comment by RachaelDMueller** [comment]
We need to decide how to apportion fuel vs. cargo spills for tank traffic.  I propose to use 50/50 to start with.  If time allows, @SusanEAllen, I can review Ryah’s spreadsheet for a more informed decision.  Does 50/50 seem like a good backup plan to you?

**Comment by SusanEAllen** [comment]
50% fuel spill seems high to me.  I don't think I've heard of a tanker spill that didn't spill some of its cargo and only spilled its fuel.  Normally fuel tanks are a bit more central and better protected I think.

**Comment by RachaelDMueller** [comment]
Nathan E. Stewart was all fuel. Perhaps a different allocation for tanker, tug and ATB?  I agree that informed decision making is a better method.  Shall I start with reviewing Ryah’s spreadsheet?

**Comment by RachaelDMueller** [comment]
As far as priorities go, I was just going to put this further down the list and start with 50/50.  Perhaps a compromise is 50/50 for tug and atb and 80/20 (cargo/fuel) for tankers with an argument that tug and atbs aren’t a fully coupled system (hence, 50/50) but tankers are and by length the chances of hitting a fuel tank side is ~4x greater...?

**Comment by SusanEAllen** [comment]
Sounds better. Maybe bounce this past Ryah?

**Comment by RachaelDMueller** [comment]
I modified CAD and US .yaml files to be more consistent and readable and [created a notebook](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_oil_type.ipynb) to select fuel type from .yaml files based on origin destination.  

Next: 
- Add fuel vs. cargo selection (e.g. discussion above)
- More testing
- Make .py script
- Finalize dilbit/akns probability based on ship track data

**Comment by RachaelDMueller** [comment]
I think most (all?) of the heavy lifting has been done and that I can cookie-cutter the fuel attribution for tank barges and ATBs.  [Here](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_oil_type_tanker.ipynb) is the notebook for tankers.  It’s based on [this google drawing flow chart](https://docs.google.com/drawings/d/1-4gl2yNNWxqXK-IOr4KNZxO-awBC-bNrjRNrt86fykU/edit).  Some behind-the-scenes changes were made to the fuel allocation yaml files to allow for a more templated approach to allocations (as well as user-friendly naming conventions).  I’ve included comments on potential problem spots that I still need to address.  I will convert to a function and do some preliminary tests.

**Comment by RachaelDMueller** [comment]
I spoke too soon.  Upon reviewing the [ATB_Oil_Attribution](https://docs.google.com/drawings/d/1Aigd2wccnl6-pQVo4KLN0xq1is6poD9z5JnFVb-fduE/edit), I realized that some significant changes were made around westridge traffic.  I have updated the flowchart.  Details to point out: 

- Westridge traffic is allocated based on Origin Canada or Westridge and destination U.S. Oil
- Suncor Nanaimo and ESSO Nanaimo are prioritized in attribution.  If origin or destination is from/to these locations, the fuel allocation will reflect what we gave for these.  I imposed this priority b/c these are the only two locations (other than Westridge) that we have information on in terms of fuel types.

@SusanEAllen and @campower, can you review my choices and make sure that you agree with them? In particular, Cam, at some point, we will want to map out the ship tracks that will be attributed as dilbit given the criteria that I’ve imposed here.  I’m aware that we will miss the track that stops in Anacortes.  I just don’t see a way to generalize the attributions to include that track w/o collateral damage...unless...we want to impose an origin of Westridge and destination of U.S. Oil manually in the shapefile for this track?

**Comment by campower** [comment]
Noted! 
> unless...we want to impose an origin of Westridge and destination of U.S. Oil manually in the shapefile for this track?

Let's discuss in our meeting tomorrow?

**Comment by RachaelDMueller** [comment]
I created a [US_all.yaml](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/US_all.yaml) to use as our generic fuel allocation for vessel tracks that:

- don’t have an origin/destination
- Are re-allocated as ATB traffic (e.g. the 5 oil-cargo ATBs with wrong COARSE_TYPE)

The notebook used to create this .yaml file is [here](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/make_cargo_AllUS.ipynb)

Generally speaking: Tankers -> crude, atbs -> gas, tugs -> bunker-C. 

I’m waiting to hear back from Bikram Kanjilal as to whether he can help shed light on marine transport of dilbit from westridge or US terminals, see, e.g., [Fred Felleman’s report](https://foe.org/resources/tar-sandsdilbit-crude-oil-movements-within-the-salish-sea/).  @SusanEAllen, this is the report I came across early on in the project that made me connect dilbit to U.S. Oil. What we’ve found, however, is that Henry Sause is no longer the tug moving this ATB traffic in 2018.  Joseph Sause is the tug in the 2018 data. We do have crude export from US terminals which is presumed to be either Bakken or Canada conventional, represented here as AKNS.  It could, however, be dilbit....

**Comment by RachaelDMueller** [comment]
Gosh this is tricky!  @campower and I just met to discuss the results of the 4-hour ship track joins.  There are nuances that Cam will speak to in tomorrow’s MIDOSS meeting.  The basic gist for ATBs is that ~75% of ATB tracks are joined to origin/destination. The remainder will have null values for origin destination.  This remainder group represents ship tracks that weren’t joined because: (a) The ship speed between chronologically ordered, AIS ship track was > 80 kts, (b) the time between tracks > 4 hrs, (c) or the the distance was less then 1 km.  Cam and I looked at all of the ship tracks not joined to origin-destination as well as the subset of voyages < 1 km (that will also have null values for origin/destination).   The first group appears to be on defined oil-transport routes whereas the second group appears to have a lot of clustering at what we assume to be anchoring locations.  Cam is going to look at the vessel time exposure for these tracks (to get a sense for how they will affect our selection process).  

Some decision points that need to be made is how to decide on fuel vs. cargo spills for these tracks, given they will all be represented the same, with null values in origin destination.  One idea that I’m working with is to tally the number of fuel transfers from oil terminals vs. cargo transfers from oil terminals for ATBs and non-ATB barges to represent the risk of cargo spill vs. fuel spill.  I’m still thinking through this approach.  Implicit in this method is that an ATB at anchor will have just as much of a likelihood of having cargo as one in transit. 

We will likely want different considerations for ATBs than traditional tank barges. 

Cam is not going to be able to have results from ATBs, tanker and tank barges in time for tomorrow’s meeting but he is going to at least give a snapshot of the problem to help support our collective understanding and decision-making.

**Comment by SusanEAllen** [comment]
Just a heads up:
The oil spill volume algorithm we have is designed for all loads: aka empty and full, pooled together.  If we are separating them by direction or otherwise, the oil spill volume algorithm needs to be re-done.

**Comment by RachaelDMueller** [comment]
I was over-thinking the problem in my above comment.  The ATBs in our list are known oil-cargo ATBs; so the un-joined tracks can be allocated “generic” fuel allocation with the chance of fuel vs. cargo spill being 20/80 split (as we’ve already determined).  

Tug barges we still need to wait and see for evaluation of ship track joins.

**Comment by RachaelDMueller** [comment]
Thanks, @SusanEAllen.  My comment was for fuel vs. cargo allocation, not volume.  A different beast.  BUT...I was typing out that I was over-thinking the problem as you submitted your comment.  I think we are good, but we can discuss tomorrow.

**Comment by SusanEAllen** [comment]
We are good.  My comment and your clarification happened at the same time.

**Comment by RachaelDMueller** [comment]
This is related to our origin-destination analysis as well as fuel type selection, so I’m posting here.  

The question I’m trying to answer is this: **How do we decide whether a tank barge that is lacking origin/destination is at risk of spilling both cargo and fuel or just fuel**?

In other words, if we select a ship track that only has the information that it’s a tug boat, how do we weight the selection of whether this tugboat is towing oil cargo or towing no/no-oil cargo? 

A strategy I came up with for weighting this decision was to evaluate the ATB/ITB data.  The idea here is that I can quantify the amount of cargo transfers from facilities to ATB/ITB and compare that value with the amount of fuel transfers from facilities to said ATB/ITBs. This value would then represent an estimate of the ratio of bunkering required for oil cargo transport.  It's just an estimate b/c some vessels may bunker in canada but get cargo in the US and visa versa.  The assumption here is that the tally of the year smooths out these inconsistencies.

The reason why I'm using ATB/ITB is b/c these vessels are identified as ATB/ITB by name.  With tugs, it's the barge, not the tug, that is named in transfer of cargo.  I figure that if I look at fuel transfers to vessels with ATB/ITB and compare to cargo transfers to tank barges with ATB/ITB then I’m most likely getting the representative information on ATB units. 

The way I thought to use this for weighting tank barges is to assume that the ratio of bunkering to cargo transfers is the same for tank barges as for ATB/ITBs. I could then use the information on the number of cargo transfers for tug barges with the ATB/ITB ratio of bunkering to cargo to estimate the amount of bunkering that would have been required by the tank barge tugs to support the tank barge traffic volume for oil barges.  Additional fueling would then represent non-oil barges.  As such, I could then compare this estimated value of oil-cargo bunkering with the total number of bunkering stops made by tank barges to get a fraction of oil cargo transport.  My thinking was that we could use this fraction to weight the unidentified tank barge traffic as being either a fuel spill risk or a cargo and fuel spill risk.

This was my thinking.

In practice, what I’m finding is that the ratio of bunkering to cargo transfers is the same for ATB/ITB identified traffic as for the general “tug”/“tank barge” traffic.  In both cases, I’m seeing **10x cargo transfers for every bunkering stop.**  That result in itself is surprising to me! 

Here is some other surprising information:  
- Fueling from oil-transfer facilities is 1% of the volume of oil cargo transfer from these facilities; whereas total fueling within WA is 15% of the net oil cargo transfer volume.  I need to unpack this a bit more to understand why.  At first, I thought the difference may represent the volume of fueling by ferries, cargo and recreational vessels; but I then learned that a good bit of tug bunkering is vessel-to-vessel transfer, which brings me to
- [HMS 26-1](http://harleymarine.com/gallery/Equipment/Spec%20Sheets/HMS261.pdf) is a fueling barge that isn’t considered "a facility".  @campower, this fueling vessel may explain some of the observed clustering that you’re seeing in the data.  

The notebook with these calculations is called [calculate_bunkering_vs_cargo_transfers](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/calculate_bunkering_vs_cargo_transfers.ipynb).

I need to review my work on the net tug bunkering and cargo transfers to make sure that I’m estimating what I think I’m estimating b/c I find it very odd that the cargo to fueling ratio is so close to that of the ATB-only traffic.  This analysis was supposed to help me answer this question but I’m afraid it has raised some!

**Comment by SusanEAllen** [comment]
So if I am understanding correctly, this would suggest the ratio of tug/barges carrying oil/other cargo = the ratio of ATB's carrying oil/other cargo.

**Comment by RachaelDMueller** [comment]
Possibly.  @SusanEAllen, I need to clarify/correct a statement I made in our meeting just now.  

Re: method.  I take all fueling (both facility and non-facility) and create a list of all tugs with ATB in the name and all barges with ATB in the name that receive either fuel or cargo.  The tugs with ATB in the name that receive fuel are: 

- [AIS] 'ATB TUG BILL GOBEL’, 
- [Charlie] 'ATB TUG MIN ZIDELL’, (listed as local vessel in AIS)
- [Charlie] 'ATB TUG JAKE SHEARER’, (not in voyage dataset)
- [AIS] 'ATB TUG VISION’, 
- [AIS] 'ATB TUG SOUND RELIANCE’,  
- [Charlie] 'ATB TUG OCEAN RELIANCE’ (listed as Tanker in AIS)

The ones with [AIS] in front are those we have identified as fuel ATBs.  The ones with [Charlie] in front are the ones identified as oil ATBs in Carlie Costanzo’s spreadsheet.  Both are outlined in @campower ’s [google spreadsheet](https://docs.google.com/spreadsheets/d/1dlT0JydkFG43LorqgtHle5IN6caRYjf_3qLrUYqANDY/edit#gid=1497885944). The above list is also shown in [my notebook](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/calculate_bunkering_vs_cargo_transfers.ipynb).  

If Charlie’s list is accurate with oil ATBs then these are all oil ATBs.  If not, then I would say that your assessment is correct, i.e. that I haven’t isolated oil traffic with my ATB selection and that we are seeing a similar split in ATBs and tugs w.r.t. oil vs. non-oil traffic.  If this list includes non-oil traffic then it makes the 10:1 ratio of cargo transfers to fueling even more surprising!  

I like your solution to use ship tracks connected with origin destination vs. those not-connected to get a weighting.  It’s an idea that Cam and I had been floating before, but I was hoping that this fuel transfer approach might prove a more accurate strategy.  Unfortunately, it turns out to open more questions!  So...back to ship track ratios!

**Comment by RachaelDMueller** [comment]
We have 16 confirmed ATBs in the Salish Sea.  One quarter of these are not included in our voyage dataset because they are listed as “other” or “local” vessel in AIS and Casey only selected vessels listed as tug or tanker. 

Details of the selections are in the [google spreadsheet ](https://docs.google.com/spreadsheets/d/1dlT0JydkFG43LorqgtHle5IN6caRYjf_3qLrUYqANDY/edit#gid=1497885944).

From department of ecology list of ATB/tugs, we identified these vessels not included in our ATB list:
2 tankers (Ocean Reliance, Jake Shearer)
2 local vessels (Dublin Sea, Nancy Peterkin)
1 other vessel (Emery Zidell)

From Charlie’s list, we identified 7 ATBs (some cross over with the above list) with MMSI that show up in our comprehensive dataset but that were not flagged as ATBs. From this list of 7 vessels, we add "Min Zidell” as another “other” vessel.

We can include these 4 “other” and “local” vessels as ATBs in our comprehensive shapefile but @campower doesn’t see a way of including them in our origin/destination list.  He is going to look at maps of these ship tracks to see if the maps show clear origin/destination pairs.  If they do, then we can fix the data with oil attributes based on origin/destination. As you can see at the bottom of [this notebook](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/make_cargo_type_WAdictionary.ipynb), origin/destination has a very strong influence on whether/where an ATB will carry bunker, diesel or crude oil.  Short of having this information, we will take an educated guess on cargo based on the generic oil attribution, as shown at the end of [this notebook](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/make_cargo_AllUS.ipynb). As  you will see in the graphic at the end of this notebook, AKNS represents a small portion of ATB fuel cargo but is 100% of atb fuel cargo for particular facilities.  

Another option to consider is whether @douglatornell would like to open the hood on the origin-destination linking to see if we can link tracks from these 4 ATBs based on their MMSI...?  @campower indicates that the script relies on a pre-selection of data and that this strategy may not work, but I pose it here for group consideration. 

For weighting oil cargo allocation for the non-atb tugs, we need:
1) Number of ship tracks that are joined origin-destination
2) Number of ship tracks that clearly go to/from oil facility but are not joined (if this a quantifiable amount?)
3) Total number of remaining ship tracks not included in (1) or (2) above.

**Comment by RachaelDMueller** [comment]
I’ve completed the coding of this piece and updated my [monte carlo folder](https://github.com/MIDOSS/analysis-rachael/tree/master/notebooks/monte_carlo) with the scripts.  Here are code bits for [testing ](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/test_oil_type_selection.ipynb)as well as for [tanker](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_oil_type_tanker.py), [ATB ](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_oil_type_atb.py)and [barge ](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_oil_type_barge.py) oil allocation scripts.  See [monte_carlo notebook](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/monte_carlo.ipynb) for the way in which I call these functions.  

The following details remain:
- Update [master yaml ](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/master.yaml) file with AIS-informed probability of cargo vs fuel spill for barges that are missing oil-terminal origin or destination (variable name is “probability_oilcargo”)
- Verify that my oil-cargo scripts will replicate oil distirubion for a particular vessel and origin or destination if called ~1000 times
- Confirm with @campower that my choices regarding atb and barge cargo allocations match shapefile design
