### ISSUE TITLE
monte-cargo: ATBs not included in origin-destination analysis

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#17]
As @campower has discovered, 5 ATBs are not included in our origin/destination analysis because they did not have a COARSE_TYPE = 31, 32, or 52, which is the COARSE_TYPE attribute to tug barges.  Of these 5, 2 were given a COARSE_TYPE of tanker, 2 were given a COARSE_TYPE of “local vessel” and 1 was given a COARSE_TYPE of “other.”  These are all US-traffic ATBs.  The question is: How do we want to handle them?  Because they are not included in Casey’s pre-selection data, they are not included in our origin-destination analysis.  As such, they will fall into the category of ship tracks that are not allocated.   What I suggested to Cam was to manually adjust the attributions for these particular MMSI vessel tracks to ATBs and then I’ll just use the Generic US-atb fuel allocations for these tracks.  Cam, I think this is the best we can do, yes?  @SusanEAllen and Cam, please let me know if (for whatever reason) you prefer a different method for how to handle these tracks.

**Comment by SusanEAllen** [comment]
I suggest we put a hold on this for the moment and return to it after the 4 hour tracks are analyzed.  I think a broader issue is what to do with unlinked tracks: either because the O-D failed or because they were excluded to start with.  Then we can wrap this issue in as well.

**Comment by RachaelDMueller** [comment]
Ah.  Okay.  I thought that we had agreed during our meeting that we would attribute the unlinked tracks by a generic US fuel allocation.  Am I hearing you correctly that you are now wanting to take a different approach with the unlinked tracks?

**Comment by RachaelDMueller** [comment]
Perhaps it’s my phrasing.  By “generic US fuel allocation” I’m meaning the combined import/export allocation that we discussed.

**Comment by SusanEAllen** [comment]
Yes, of course, it is within the bigger issue and this suggestion is the same solution.  Excellent.
