### ISSUE TITLE
Thickness gradient values for Dilbit, AKNS, Diesel, Gas, and Bunker-C

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#2]
USERCOEFVELMANCHA, value range: 5-30.  We are currently using default values for all but the different oil types will have different values.  

We need:
- Values for Dilbit, AKNS, Diesel, Gas, and Bunker-C
- Publication-ready references for the above

NOTE: I include gas for a contingency plan if I can’t get our diesel case working in time for monte carlo simulation (with the caveat that the problem may not just be a diesel-case problem)

**Comment by RachaelDMueller** [comment]
Note to Haibo from Rodrigo [july 2, 2020]:

First point:
“The model suggest a typical value of 5-30 and she is wondering how to decide on an appropriate values for different oil types (light vs heavy).”
This was my work done when finalizing my graduation (where I developed the oil spill module).
I suggest to you the following link: http://www.mohid.com/PublicData/Products/Thesis/TFC_RodrigoFernandes.pdf
Unfortunately it’s in Portuguese. I suggest your colleague translate it, and check page 35 specifically.
Anyway, UserCoefVelMancha is a parameterization value, when computing spreading with thickness gradient method (which is a method I created, based in Fay formulations). This thickness gradient method is dependent on the computational mesh and number of particles used (in addition to the substance selected). My suggestion is you do the following:

- Compute Fay’s theorical area evolution (MOHID can do that, as a matter of fact)
- Run an oil spill without any kind of advection (no wind, no hydrodynamics, no waves / stokes drift). The oil should move horizontally only based on spreading process. Start by using UserCoefVelMancha with the value of 10 (default value).
- Compare the obtained values for area using thickness gradient method vs. theorical area. Values should be as close as possible.
- Change the UserCoefVelMancha in order to approximate as much as possible the area computed by thickness gradient to the theorical area.

Note that if you use very low number of lagrangian particles and very low spatial resolution, results will be always bad.
Once you find a nice compromise with the previous procedure, you could now plug in the advection.
 
Second point:
“how to relate the UserCoefVelMancha parameter with the equation 31 in your PhD thesis”
In my PhD, I don’t describe the thickness gradient method for spreading (which I don’t use much, because is too much dependent from user calibration, and our application of oil spill model is mainly operational, so we tend to use simpler methods that require less calibration).  But there must be a connection, because the thickness gradient method is derived from Fay method, but with an additional coefficient.  You should look for correspondence between line 3593 with line 3710 (and forward), and then look for equations in both my PhD or the TFC.

I’m sorry for not having the time currently to go through the equations and explain them, I would need a couple of hours to derive it and analyze it carefully, and I can’t do it at the moment…(I would have to take it from my free time, which is limited, as well). I understand that maybe the explanation is not so clear.
Kind regards,
Rodrigo

**Comment by SusanEAllen** [comment]
See attached translation of thesis pg 36.
[MOHID_thesis_4.1.1.pdf](https://github.com/MIDOSS/MIDOSS-MOHID-config/files/4886999/MOHID_thesis_4.1.1.pdf)

**Comment by SusanEAllen** [comment]
Given Rodrigo's comments above, why don't we just use the Fay's theoretical area evolution, as the method seems to be to tune the thickness gradient method to get the Fay's value?

**Comment by RachaelDMueller** [comment]
I’ll look into this and respond once I hand off to Doug the monte carlo code

**Comment by RachaelDMueller** [comment]
Using Fay’s spreading method
