### ISSUE TITLE
U.S. oil cargo by vessel .yaml file

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#5]
Create a .yaml file for incoming and outgoing tanker, atb and barge that lists percent traffic (weighting) for 7 oil type (dilbit, crude, bunker-c, diesel, gas, jet, other).  Something like:

We may need to change this to narrow down on incoming and out-going locations as fuel types are likely differentiated by origin/destination.  For example, the westridge-U.S. oil dilbit transport is unique.  

**incoming (by terminal location)**
    1.  Tanker
         - dilbit: 0%
         - crude: 68%
         - bunker-c: 7%
         - diesel: 6%
         - gas: 9%
         - jet: 3%
         - other: 7%
    2. ATB  (same format as above)...
    3. Tank barge (same format as above)...
**outgoing (by terminal location)**
    1.  Tanker(same format as above)...
    2. ATB(same format as above)...
    3. Tank barge (same format as above)...

**Comment by RachaelDMueller** [comment]
This has turned out to be tricky owing to data quality issue.  My plan was to use the Facility information to flag origin/destination; but, as it turns out, some vessels are labeled as Facilities in the Dept. of Ecology data set.  I finally settled on a method that I think will work just fine for what we need, though it’s a first draft and will likely need revision(s).  

The .yaml files have a weird error in them that I don’t yet understand and need to fix.  I also need to calculate and add the percentage of total category. Here is the [cargo_by_origin.yaml](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/cargo_by_origin.yaml) and the [cargo_by_destination.yaml](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/cargo_by_destination.yaml), with the [notebook here](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/oil_by_destination_and_vessel.ipynb)

**Comment by douglatornell** [comment]
Are the weird errors that you see the `!!python/object/apply:...` things?

**Comment by RachaelDMueller** [comment]
Yes, @douglatornell.  That’s exactly what I was referring to.  A quick search last night makes me think this is a version issue, but I haven’t yet done my troubleshooting work.  Thoughts?

**Comment by douglatornell** [comment]
`!!python/object/apply:...` is how Python objects that don't fit into the YAML types model are represented; details are in the "YAML tags and Python types" section of https://pyyaml.org/wiki/PyYAMLDocumentation. (Sorry, the PyYAML docs aren't deep-linkable, so you will have to search for that title on the page.

HOWEVER! We want to avoid putting Python objects into YAML files because it is a known security vulnerability. You should write your YAML files using `yaml.safe_dump()` and read them using `yaml.safe_load()`. When you do that `safe_dump()` will raise an error about the things that would produce `!!python/object/apply:...` things. Likewise, `safe_load()` will refuse to read them.

So, now the issue is how to avoid the items that `safe_dump()` will complain about.

I think that `total_gallons: !!python/object/apply:numpy.core.multiarray.scalar` is saying that the value is a single number from a Numpy array. Try changing your code to (for example):
`destination[f'{label}']['tanker']['crude']['total_gallons'] += df.TransferQtyInGallon[row].item()`
The `.item()` method call on the end copies an array element into a Python scalar that `safe_dump()` should be happy with. Docs: https://numpy.org/devdocs/reference/generated/numpy.ndarray.item.html#numpy.ndarray.item

It looks like there is something a little different happening for tanker bunker. Is TransferQtyInGallon a single number there, or an array maybe?

**Comment by RachaelDMueller** [comment]
adding ".item()" and "safe_dump" did the trick perfectly, @douglatornell.  Thanks!

**Comment by RachaelDMueller** [comment]
Getting closer.  @campower, I just need to add the Canada fuel types to the cargo files.  This is the list that I’m using:

- ESSO Nanaimo Departure Bay
- Suncor Nanaimo
- Shell Chemainus Bare Point
- Chevron Cobble Hill
- Chevron Stanovan
- Barge Mooring Near Stanovan
- Shell Shellburn
- Westridge Marine Terminal
- ESSO IOCO Vancouver
- Suncor Vancouver

Do all of these locations have tanker, tug, and atb traffic?  It doesn’t really matter in the sense that I can include them in the file at no extra cost.  Just curious. 

 I’ve updated [the excel spreadsheet](https://docs.google.com/spreadsheets/d/1bIQk9YNfcCjf690KKgcdRO7HyEYj6rmJ97HRWR_S82g/edit#gid=0) to show information on fuel type.  Not much to go on.  I think the best bet is to use diesel everywhere except Suncor Nanaimo and Westridge as those are the only two places that we have known information on non-diesel fuel.  For Westridge, I think I want to apportion fuel based on traffic volume.  For example, if ten vessel leave westridge each week then I’ll portion 1/10 as dilbit and 9/10 as AKNS (as representing Canadian, non-dilbit crude).  The assumption here is no refined export.  

@SusanEAllen, do you agree with this approach for fuel allocation for Canadian tank traffic or do you want different allocations?

**Comment by RachaelDMueller** [comment]
Before moving to the next step, I wanted to QAQC the dilbit to U.S. Oil traffic.   It appears that there are only 6 transfers of crude to U.S. Oil & Refining in 2018.  These transfers were made by tank barge DRAKES BAY. 

This may not be value-added information.  @campower, shall I script up dilbit cargo using origin equal to 'Westridge Marine Terminal' and destination equal to 'U.S. Oil & Refining’ for vessel type ‘tug’ (or tank barge)?  Do 6 transfers in this category match what you’re seeing?

**Comment by campower** [comment]
> Do all of these locations have tanker, tug, and atb traffic?

Yes, the ten that you listed have tanker/tug/atb traffic!

> shall I script up dilbit cargo using origin equal to 'Westridge Marine Terminal' and destination equal to 'U.S. Oil & Refining’ for vessel type ‘tug’ (or tank barge)? Do 6 transfers in this category match what you’re seeing?

I'll report back on this after linking the origin/destination output to the vessel tracks. Stay tuned!

**Comment by RachaelDMueller** [comment]
I’m seeing ITBs (Integrated Tank Barges) in DOE database and am changing my scripts to include ITBs in our ATB category

**Comment by RachaelDMueller** [comment]
I added Jupyter Lab notebooks for creating the [Pacific Origin](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/make_cargo_OriginPacific_dictionary.ipynb) and [U.S. Origin](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/make_cargo_OriginUS_dictionary.ipynb) fuel types together with .yaml files for [Pacific origin](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/Pacific_origin.yaml) and [U.S. origin](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/US_origin.yaml) fuel (organized by vessel type) 

The jupyter notebooks include overview graphics of fuel types by vessel types at the bottom of the notebooks in order to show how the fuel allocation will vary by vessel type.  

The .yaml files show the number of transfers for each vessel type and fuel type in order to get a sense of the traffic volume.  

Together, these files show a good deal of variation!  These will be the generic cases for vessels that aren’t attributed to a specific origin/destination.  The numbers are based on all fuel transfers to/from facilities and from/to vessels.  Thus, these numbers reflect total import/export and not just import/export to our selection of oil transfer facilities.  I can change this if/as desired, though this approach seems to me to be the best one considering what I know about the origin/destination analysis.  

@campower, please let me know if you think the “leftover” tracks are best allocated with a different selection of transfer sites. 

@SusanEAllen, I think the graphics will perhaps answer some of the questions you raised in your email(s)...?

**Comment by RachaelDMueller** [comment]
@SusanEAllen, as promised, here are the notebooks that show general characteristics of import and exports.  There are 4 notebooks total, two that analyze all oil traffic [import](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/graphics/Oil_transport/Oil_Cargo_WA_import.ipynb) and [export](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/graphics/Oil_transport/Oil_Cargo_WA_export.ipynb) data and two that analyze the oil traffic [import](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/graphics/Oil_transport/Oil_Cargo_WA_import_Casey.ipynb) and [export](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/graphics/Oil_transport/Oil_Cargo_WA_export_Casey.ipynb) to the marine terminals used in our origin/destination analysis.  I created these notebooks as a strategy of answering the questions you raised about the representation of general characteristics of oil transport.  

The numbers that I had in mind during our discussion were actually related to the representation of fuel, not locations.  The selection of crude, bunker, diesel (2 types), gas, and jet fuel  account for 93% of imported fuel types and 89% of exported fuel types.  I can also answer the question of the representation of total traffic as well. Here are the numbers for the representation of total traffic:

- Total volume imports from WA in 2018 is ~5.7 billion gallons (94% tankers, 5.5% atb, ~1% tug barges)
- Total volume exports from WA in 2018 is ~4.4 billion gallons (71% by tankers, 26% by ATBs)
-  Our origin/destination locations account for 87% of oil import (~5.0 billion gallons)
-  Our origin/destination locations account for 78% of oil exports (~3.5 billion gallons)

By in large, we import crude and export refined.  Fuel type is highly variable by location. These numbers show that tanker traffic and location of origin/destination of tanker traffic is our best bet for nailing down the macro scale of fuel transport.  Second to that is ATB traffic, followed by tug-barge.  

NOTE: the “All WA” data referenced above is really Salish-Sea specific as it does not include traffic to counties outside the Salish Sea.
