### ISSUE TITLE
Decide values to save to .netcdf in hdf5-to-netcdf4

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#6]
Below is a list of current netcdf output with values that are currently considered to keep as bold.  Deliverable goals include:
- producing information on response time by location (beaching time scales)
- Volume of oil beached (Thickness_2D and Beaching_Time)
- absence/presence of oil on surface (Thickness_2D)
- amount of oil in water (OilConcentration_3D)

Dimensions:              (grid_x: 396, grid_x_latlon: 397, grid_y: 896, grid_y_latlon: 897, grid_z: 40, time: 191)
Coordinates:
  * **time                 (time) datetime64[ns] 2017-11-21T00:30:00 ... 2017-11-28T22:30:00
  * grid_y               (grid_y) int16 0 1 2 3 4 5 ... 890 891 892 893 894 895
  * grid_x               (grid_x) int16 0 1 2 3 4 5 ... 390 391 392 393 394 395
  * grid_z               (grid_z) int16 0 1 2 3 4 5 6 7 ... 33 34 35 36 37 38 39**
  * grid_y_latlon        (grid_y_latlon) float32 0.0 1.0 2.0 ... 895.0 896.0
  * grid_x_latlon        (grid_x_latlon) float32 0.0 1.0 2.0 ... 395.0 396.0
Data variables:
    OilConcentration_2D  (time, grid_y, grid_x) float64 ...
    **Thickness_2D         (time, grid_y, grid_x) float64 ...**
    Dissolution_3D       (time, grid_z, grid_y, grid_x) float64 ...
    **OilConcentration_3D  (time, grid_z, grid_y, grid_x) float64 ...
    Latitude             (grid_y_latlon, grid_x_latlon) float64 ...
    Longitude            (grid_y_latlon, grid_x_latlon) float64 ...
    Beaching_Time        (grid_y, grid_x) datetime64[ns] ...**
    Beaching_Volume      (grid_y, grid_x) datetime64[ns] ...
    Oil_Arrival_Time     (grid_y, grid_x) datetime64[ns] ...

**Comment by RachaelDMueller** [comment]
Note: Beaching_Volume does not contain volume information

**Comment by douglatornell** [comment]
Don't worry about removing unused variables to reduce file size. `Lagrangian*.nc` files are ~25Mb - i.e. small in the scheme of things because of integer/scale-factor compression. Likewise, don't worry too much about adding variables that you might need.

If storage becomes a concern, getting rid of the (AFIK) useless ~11Gb `Turbulence*.hdf5` will be literally orders of magnitude more helpful.

**Comment by RachaelDMueller** [comment]
LOL...alright.  I’m going to resolve this issue and start a new one that is just about deciding what we need.
