### ISSUE TITLE
monte carlo: get_date

### ISSUE THREAD

**Issue by RachaelDMueller** [MIDOSS/MIDOSS-MOHID-config#8]
Function for random selection of date.  First draft [here](https://github.com/MIDOSS/analysis-rachael/tree/master/notebooks/monte_carlo).  

**Refinements (in progress):**
- Weight selection by net monthly vessel traffic exposure as calculated from geotiffs. This refinement follows our assumption that accidents are a function of VTE and not vessel type.  This assumption is consistent with assumptions made in studies based on focus vessel traffic.  We need to consider if it’s appropriate to apply it to non-focus vessel traffic or whether we need to separate the traffic.  The reason we may choose to separate is if focus vessel traffic is fairy uniform across seasons.  If so then we may be under-weighting higher-wind conditions by biasing with summer, non-focus-vessel traffic.
- The notebook uses a delta_time of 30-minutes, but I’m now seeing that my reasoning for this choice was wonky.  Change back to 1-hr interval.

**Comment by RachaelDMueller** [comment]
We will be able to answer the question about seasonality of tank traffic when @campower finished the GeoTIFF files.  I’m leaving this as-is to cycle back and refine next week.

**Comment by SusanEAllen** [comment]
What would be the underlying assumption on oil spill probability then, if we weight differently based on tank traffic?

**Comment by RachaelDMueller** [comment]
Same.  It would just differentiate the lower-capity spill from higher-capacity spills.  I flag it here as something to consider.  I’m going to hold of on considering this more until we have the information from the GeoTIFFs, though I also understand that it depends on which question we really want to answer.  If we want to answer from an oceanographic perspective then I can see value in differentiating traffic that has seasonality from traffic that does not have seasonality but the assumption would be the same within these groups.

**Comment by SusanEAllen** [comment]
We can process the final results to look at these issues.*  Not need to further complicate the Monte Carlo calculations if our basic premise is that all are equal.

* ie use the .csv file to pull out all low-capacity spills and compare the aggregate results from that to all high-capacity spills.

**Comment by RachaelDMueller** [comment]
As long as weighting the monte we choose by VTE doesn’t lead to disproportionately selecting summer focus vessel traffic (assuming that we will disproportionately end up selecting summer months with this method) and that we get a monthly spread of focus vessels that reflects the monthly trend...then...yet...the CSV file would work just fine and the bias that I’m concerned about won’t be an issue.  Similarly, we may choose to ignore the bias anyway.  Just flagging it to consider.

**Comment by SusanEAllen** [comment]
If we have 100 focus vessels each month but 100 recreational vessels in summer only.  Then think about 3 average dice rolls:
We will get 2 for summer and 1 for winter.
Of the 2 for summer, when we go into the next stage, 1/2 the time we'll choose focus and 1/2 recreational vessels.
So of the three rolls, there will be equal probability of winter or summer focus vessels.

**Comment by RachaelDMueller** [comment]
Cleaning up my comments to say that I’m 100% with you, @SusanEAllen.  I am also looking forward to educating myself a bit more with the data and think it’s prudent to keep an eye out for ways in which our method may unintentionally bias.  That’s really the core of my little “sticky note” comment here.  It helps me to add “sticky notes” like this when I’m in the middle of problem solving other details and in a higher-distraction environment so that I can flag them to return to consider later.

**Comment by RachaelDMueller** [comment]
I think this gets back to your point about not yet knowing how many runs will be enough.

**Comment by RachaelDMueller** [comment]
[python script](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_date.py)

[development notebook](https://github.com/MIDOSS/analysis-rachael/blob/master/notebooks/monte_carlo/get_date.ipynb)

This is mostly complete.  I’m not yet closing b/c the n_locations flag doesn’t do anything yet and the function only returns one date.  

Highest traffic is in August.  traffic location for summer months will be different than tank traffic locations so I still see this as a little different then the dice roll problem with potential for biasing but...we shall see....
